// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uchat.Database.Context;

#nullable disable

namespace Uchat.Database.Migrations
{
    [DbContext(typeof(UchatDbContext))]
    partial class UchatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanCustomizeGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanInviteUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanPinMessages")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendMessages")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendMusic")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendPhotos")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendStickers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DefaultCanSendVideos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentChatRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlowModeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMessagesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("IX_ChatRooms_CreatorId");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("IX_ChatRooms_LastActivityAt");

                    b.HasIndex("ParentChatRoomId")
                        .HasDatabaseName("IX_ChatRooms_ParentChatRoomId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_ChatRooms_Type");

                    b.ToTable("ChatRooms", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoomMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvitedById")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvitedById");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChatRoomMembers_UserId");

                    b.HasIndex("ChatRoomId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChatRoomMembers_ChatRoom_User");

                    b.ToTable("ChatRoomMembers", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoomMemberPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanBanUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanCustomizeGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanDeleteMessages")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanInviteUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanManageInviteLinks")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanManageTopics")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanPinMessages")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanPromoteMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanRemoveUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanRestrictUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendMessages")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendMusic")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendPhotos")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendStickers")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSendVideos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatRoomMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChatRoomMemberPermissions_MemberId");

                    b.ToTable("ChatRoomMemberPermissions", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ContactUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactUserId")
                        .HasDatabaseName("IX_Contacts_ContactUserId");

                    b.HasIndex("OwnerId", "ContactUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Contacts_Owner_Contact");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("IX_Friendships_ReceiverId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Friendships_Status");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("IX_Friendships_Receiver_Status");

                    b.HasIndex("SenderId", "ReceiverId")
                        .IsUnique()
                        .HasDatabaseName("IX_Friendships_Sender_Receiver");

                    b.HasIndex("SenderId", "Status")
                        .HasDatabaseName("IX_Friendships_Sender_Status");

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_IsRevoked_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(190)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Uchat.Database.Entities.UserSecurityToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecurityToken");
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoom", b =>
                {
                    b.HasOne("Uchat.Database.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uchat.Database.Entities.ChatRoom", "ParentChatRoom")
                        .WithMany("Topics")
                        .HasForeignKey("ParentChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("ParentChatRoom");
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoomMember", b =>
                {
                    b.HasOne("Uchat.Database.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Members")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uchat.Database.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Uchat.Database.Entities.User", "User")
                        .WithMany("ChatRoomMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("InvitedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoomMemberPermissions", b =>
                {
                    b.HasOne("Uchat.Database.Entities.ChatRoomMember", "Member")
                        .WithOne("Permissions")
                        .HasForeignKey("Uchat.Database.Entities.ChatRoomMemberPermissions", "ChatRoomMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Uchat.Database.Entities.Contact", b =>
                {
                    b.HasOne("Uchat.Database.Entities.User", "ContactUser")
                        .WithMany()
                        .HasForeignKey("ContactUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uchat.Database.Entities.User", "Owner")
                        .WithMany("Contacts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Uchat.Database.Entities.Friendship", b =>
                {
                    b.HasOne("Uchat.Database.Entities.User", "Receiver")
                        .WithMany("ReceivedFriendshipRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uchat.Database.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Uchat.Database.Entities.RefreshToken", b =>
                {
                    b.HasOne("Uchat.Database.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uchat.Database.Entities.UserSecurityToken", b =>
                {
                    b.HasOne("Uchat.Database.Entities.User", "User")
                        .WithMany("SecurityTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Uchat.Database.Entities.ChatRoomMember", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Uchat.Database.Entities.User", b =>
                {
                    b.Navigation("ChatRoomMemberships");

                    b.Navigation("Contacts");

                    b.Navigation("ReceivedFriendshipRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SecurityTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
